version: 2
jobs:
  test:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Building Docker throught docker-compose
          command: docker-compose build

      - run:
          name: Creating database
          command: |
            docker-compose run --rm -e RAILS_ENV=test web rake db:setup

      - run:
          name: Running tests
          command: |
            docker-compose run --rm -e RAILS_ENV=test web rspec

  publish_image:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Configuring Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet auth configure-docker

      - run:
          name: Configuring newrelic
          command: gsutil cp gs://kubernetes-config/newrelic.yml ./config/

      - run:
          name: Building Docker image
          command: |
            docker build -t gcr.io/${GOOGLE_PROJECT_ID}/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG .

      - run:
          name: Publishing Quacker Image in GCR Repository
          command: |
            docker info
            docker tag gcr.io/${GOOGLE_PROJECT_ID}/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG gcr.io/${GOOGLE_PROJECT_ID}/$CIRCLE_PROJECT_REPONAME:latest
            docker push gcr.io/${GOOGLE_PROJECT_ID}/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG
            docker push gcr.io/${GOOGLE_PROJECT_ID}/$CIRCLE_PROJECT_REPONAME:latest

  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Configuring Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet auth configure-docker

      - run:
          name: Setting up cluster credentials
          command: gcloud container clusters get-credentials $GOOGLE_CLUSTER_NAME --region $GOOGLE_COMPUTE_ZONE

      - run:
          name: Setting up deployment
          command: kubectl set image deployment/$KUBERNETES_DEPLOYMENT_NAME ${KUBERNETES_DEPLOYMENT_CONTAINER}=gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - publish_image:
          requires:
            - test
          filters:
            tags:
              only: /release-.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - publish_image
          filters:
            tags:
              only: /release-.*/
            branches:
              ignore: /.*/
