apiVersion: v1
kind: Service
metadata:
 name: quackerweb
 labels:
   app: quacker
spec:
 selector:
   app: quacker
   tier: web
 ports:
 - name: http
   port: 80
   targetPort: 3000
   protocol: TCP
 type: LoadBalancer
